//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoughtFlower
    {
        public int BuyID { get; set; }
        public int FlowerID { get; set; }
        public int Number { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Buy Buy { get; set; }
        public virtual Flower Flower { get; set; }
    }
}
