//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buy()
        {
            this.BoughtFlower = new HashSet<BoughtFlower>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Greenhouse_ID { get; set; }
        public string SalesPerson_ID { get; set; }
        public Nullable<int> Total_peyment { get; set; }
        public Nullable<System.DateTime> Buy_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoughtFlower> BoughtFlower { get; set; }
        public virtual GreenHouse GreenHouse { get; set; }
        public virtual SalesPerson SalesPerson { get; set; }
    }
}
