//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flower
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flower()
        {
            this.BoughtFlower = new HashSet<BoughtFlower>();
            this.FlowersInOrder = new HashSet<FlowersInOrder>();
        }
    
        public int ID { get; set; }
        public string Flower_name { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Flower_color_ID { get; set; }
        public Nullable<int> Lasting_Time { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> Type_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoughtFlower> BoughtFlower { get; set; }
        public virtual Colour Colour { get; set; }
        public virtual FlowerType FlowerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlowersInOrder> FlowersInOrder { get; set; }
    }
}
