//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ContosoUniversityEntities1 : DbContext
    {
        public ContosoUniversityEntities1()
            : base("name=ContosoUniversityEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoughtFlower> BoughtFlower { get; set; }
        public virtual DbSet<Buy> Buy { get; set; }
        public virtual DbSet<Colour> Colour { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Flower> Flower { get; set; }
        public virtual DbSet<FlowersInOrder> FlowersInOrder { get; set; }
        public virtual DbSet<FlowerType> FlowerType { get; set; }
        public virtual DbSet<GreenHouse> GreenHouse { get; set; }
        public virtual DbSet<GreenHousePhones> GreenHousePhones { get; set; }
        public virtual DbSet<Occasion> Occasion { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Packaging> Packaging { get; set; }
        public virtual DbSet<SalesPerson> SalesPerson { get; set; }
    
        public virtual ObjectResult<GetBuyReport_Result> GetBuyReport(Nullable<int> buyID)
        {
            var buyIDParameter = buyID.HasValue ?
                new ObjectParameter("BuyID", buyID) :
                new ObjectParameter("BuyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBuyReport_Result>("GetBuyReport", buyIDParameter);
        }
    }
}
