//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContosoUniversityEntities2 : DbContext
    {
        public ContosoUniversityEntities2()
            : base("name=ContosoUniversityEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<consignee_manageme> consignee_manageme { get; set; }
        public virtual DbSet<goods_info> goods_info { get; set; }
        public virtual DbSet<user_info> user_info { get; set; }
    }
}
