//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace WebApplication2.Models
{
    public class MustBeEvenAttribute : DataTypeAttribute
    {
        public MustBeEvenAttribute() : base(DataType.Text)
        {
            this.ErrorMessage = "必須為偶數";
        }

        public override bool IsValid(object value)
        {
            if (value == null)
            {
                return true;
            }

            int data = Convert.ToInt32(value);

            return (data % 2 == 0);
        }
    }
}