//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public string Order_type { get; set; }
        public Nullable<System.DateTime> Shop_date { get; set; }
        public Nullable<int> Occasion_ID { get; set; }
        public Nullable<int> Package_ID { get; set; }
        public Nullable<int> Wrapping_price { get; set; }
        public Nullable<int> Total_Cost { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Final_Cost { get; set; }
        public string More_info { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Occasion Occasion { get; set; }
        public virtual Packaging Packaging { get; set; }
    }
}
